# https://www.gitpod.io/docs/references/gitpod-yml
# image:
#   file: Dockerfile.devcontainer
#   context: .
tasks:
  - env:
      WITH_VENV: true
    init: |
      brew install go-task/tap/go-task
      task venv:clean venv:install
    command: |
      brew install go-task/tap/go-task
      task validate:static
      task --list
github:
  prebuilds:
    master: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: prevent-merge-on-error
    addComment: true
vscode:
  extensions:
    - ms-python.python
    - redhat.vscode-yaml
    - redhat.vscode-xml
    - stardog-union.stardog-rdf-grammars
    - lextudio.restructuredtext
    - trond-snekvik.simple-rst
    - EditorConfig.EditorConfig
    - paulvarache.vscode-taskfile
    - stardog-union.vscode-stardog-languages
